//! Spec-driven integration tests for ISO 8583 parser + builder.
//!
//! Test vectors are hand-constructed from the ISO 8583-1987 wire format
//! convention (not generated by the codec itself), so they validate the
//! implementation against the spec rather than against itself.
//!
//! Bitmap math (recomputed by hand for every vector, never copied from the
//! parser output, per CLAUDE.md §4.1 ③ "measurement and subject must not
//! share a source"):
//!
//!   field N --> byte (N-1)/8, bit mask 1 << (7 - (N-1)%8)
//!
//! Examples used below:
//!   field  2 -> byte 0, mask 0x40
//!   field  3 -> byte 0, mask 0x20
//!   field  4 -> byte 0, mask 0x10
//!   field  7 -> byte 0, mask 0x02
//!   field 48 -> byte 5, mask 0x01
//!   field 70 -> byte 8, mask 0x04  (secondary bitmap; primary bit 1 = byte 0 0x80)

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::collections::BTreeMap;
use wf_codec::iso8583::{build, parse, BuildError, Iso8583Message, ParseError};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Concatenate byte slices into a single `Vec<u8>` for readable test vectors.
fn cat(parts: &[&[u8]]) -> Vec<u8> {
    let mut out = Vec::new();
    for p in parts {
        out.extend_from_slice(p);
    }
    out
}

/// Build an `Iso8583Message` from `(field_number, raw_bytes)` pairs.
fn msg(mti: &[u8; 4], entries: &[(u8, &[u8])]) -> Iso8583Message {
    let mut fields: BTreeMap<u8, Vec<u8>> = BTreeMap::new();
    for (n, data) in entries {
        fields.insert(*n, data.to_vec());
    }
    Iso8583Message { mti: *mti, fields }
}

// ---------------------------------------------------------------------------
// A. Spec vectors: hand-crafted hex -> expected field set
// ---------------------------------------------------------------------------

/// A1. Minimal: only MTI + empty primary bitmap (8 zero bytes). 12 bytes total.
#[test]
fn parse_minimal_mti_only_empty_bitmap() {
    let wire: &[u8] = b"0800\x00\x00\x00\x00\x00\x00\x00\x00";
    assert_eq!(wire.len(), 12);

    let got = parse(wire).expect("minimal message must parse");
    assert_eq!(&got.mti, b"0800");
    assert!(
        got.fields.is_empty(),
        "no bits set in bitmap -> no fields, got {:?}",
        got.fields
    );
}

/// A2. Authentication skeleton: MTI 0200 + fields 3 (n6) + 4 (n12) + 7 (n10).
///
/// Bitmap byte 0 = 0x20 (f3) | 0x10 (f4) | 0x02 (f7) = 0x32.
/// All other bitmap bytes are 0x00.
#[test]
fn parse_mti_0200_fields_3_4_7() {
    let wire = cat(&[
        b"0200",
        b"\x32\x00\x00\x00\x00\x00\x00\x00",
        b"000000",       // f3, fixed 6
        b"000000010000", // f4, fixed 12
        b"1130120000",   // f7, fixed 10
    ]);

    let got = parse(&wire).expect("authentication skeleton must parse");
    assert_eq!(&got.mti, b"0200");
    assert_eq!(got.fields.len(), 3);
    assert_eq!(got.fields.get(&3).unwrap().as_slice(), b"000000");
    assert_eq!(got.fields.get(&4).unwrap().as_slice(), b"000000010000");
    assert_eq!(got.fields.get(&7).unwrap().as_slice(), b"1130120000");
}

/// A3. LLVAR field 2 (PAN, n..19). Length prefix is 2 ASCII digits.
///
/// Bitmap byte 0 = 0x40 (f2 only).
/// Parser must strip the "16" length prefix; stored value is 16 raw bytes.
#[test]
fn parse_llvar_field_2_pan() {
    let wire = cat(&[
        b"0200",
        b"\x40\x00\x00\x00\x00\x00\x00\x00",
        b"16",
        b"4111111111111111",
    ]);

    let got = parse(&wire).expect("LLVAR PAN must parse");
    assert_eq!(&got.mti, b"0200");
    assert_eq!(got.fields.len(), 1);
    assert_eq!(
        got.fields.get(&2).unwrap().as_slice(),
        b"4111111111111111",
        "stored value must NOT include the LL length prefix"
    );
}

/// A4. LLLVAR field 48 (an..999). Length prefix is 3 ASCII digits.
///
/// Bitmap: byte 5 = 0x01.
#[test]
fn parse_lllvar_field_48() {
    let wire = cat(&[
        b"0200",
        b"\x00\x00\x00\x00\x00\x01\x00\x00",
        b"011",
        b"HELLO WORLD",
    ]);

    let got = parse(&wire).expect("LLLVAR field 48 must parse");
    assert_eq!(&got.mti, b"0200");
    assert_eq!(got.fields.len(), 1);
    assert_eq!(got.fields.get(&48).unwrap().as_slice(), b"HELLO WORLD");
}

/// A5. Secondary bitmap activated by a field in the 65..=128 range.
///
/// field 70 (n3, fixed) lives in the secondary bitmap. Setting any bit there
/// REQUIRES primary bit 1 (= byte 0 mask 0x80) to be set so the parser knows
/// the bitmap is 16 bytes long.
///
/// Primary byte 0  = 0x80 (bit 1: "secondary present")
/// Secondary byte 0 (= total byte 8) = 0x04 (f70)
#[test]
fn parse_secondary_bitmap_field_70() {
    let wire = cat(&[
        b"0200",
        b"\x80\x00\x00\x00\x00\x00\x00\x00", // primary
        b"\x04\x00\x00\x00\x00\x00\x00\x00", // secondary
        b"301",                              // f70 fixed 3
    ]);

    let got = parse(&wire).expect("secondary-bitmap message must parse");
    assert_eq!(&got.mti, b"0200");
    // field 1 is the "secondary bitmap present" marker; per the public API
    // contract this is consumed by the parser and not surfaced as a payload
    // field. Only field 70 should remain.
    assert_eq!(got.fields.get(&70).unwrap().as_slice(), b"301");
    assert!(
        !got.fields.contains_key(&1),
        "field 1 (secondary-bitmap presence flag) must not appear as a data field, got {:?}",
        got.fields.keys().collect::<Vec<_>>()
    );
}

// ---------------------------------------------------------------------------
// B. Build -> wire byte equality (build is the inverse of A2/A5)
// ---------------------------------------------------------------------------

/// B1. Inverse of A2: build the message and assert it matches the A2 wire bytes.
#[test]
fn build_matches_a2_wire() {
    let m = msg(
        b"0200",
        &[(3, b"000000"), (4, b"000000010000"), (7, b"1130120000")],
    );
    let expected = cat(&[
        b"0200",
        b"\x32\x00\x00\x00\x00\x00\x00\x00",
        b"000000",
        b"000000010000",
        b"1130120000",
    ]);

    let got = build(&m).expect("build must succeed for valid fixed fields");
    assert_eq!(got, expected);
}

/// B2. Inverse of A5: secondary-bitmap message.
#[test]
fn build_matches_a5_wire() {
    let m = msg(b"0200", &[(70, b"301")]);
    let expected = cat(&[
        b"0200",
        b"\x80\x00\x00\x00\x00\x00\x00\x00",
        b"\x04\x00\x00\x00\x00\x00\x00\x00",
        b"301",
    ]);

    let got = build(&m).expect("build must succeed for secondary-bitmap message");
    assert_eq!(got, expected);
}

// ---------------------------------------------------------------------------
// C. Parse -> Build -> wire equivalence
// ---------------------------------------------------------------------------

/// C1. Round-trip A3 (LLVAR PAN): parse wire, build it back, expect byte
/// identity. This exercises that the builder re-emits the length prefix that
/// the parser stripped.
#[test]
fn roundtrip_a3_llvar_pan() {
    let wire = cat(&[
        b"0200",
        b"\x40\x00\x00\x00\x00\x00\x00\x00",
        b"16",
        b"4111111111111111",
    ]);

    let parsed = parse(&wire).expect("A3 wire must parse");
    let rebuilt = build(&parsed).expect("rebuild must succeed");
    assert_eq!(
        rebuilt, wire,
        "parse -> build must reproduce the original wire bytes",
    );
}

/// C2 (bonus). Round-trip A4 (LLLVAR) — ensures 3-digit prefix is re-emitted.
#[test]
fn roundtrip_a4_lllvar() {
    let wire = cat(&[
        b"0200",
        b"\x00\x00\x00\x00\x00\x01\x00\x00",
        b"011",
        b"HELLO WORLD",
    ]);

    let parsed = parse(&wire).expect("A4 wire must parse");
    let rebuilt = build(&parsed).expect("rebuild must succeed");
    assert_eq!(rebuilt, wire);
}

// ---------------------------------------------------------------------------
// D. Error paths
// ---------------------------------------------------------------------------

/// D1. Truncated input: only 2 bytes -> InsufficientBytes.
#[test]
fn parse_insufficient_bytes_two_byte_input() {
    let err = parse(b"02").expect_err("2-byte input must fail");
    assert!(
        matches!(err, ParseError::InsufficientBytes { .. }),
        "expected InsufficientBytes, got {err:?}",
    );
}

/// D2. MTI contains non-ASCII-digit bytes -> InvalidMti carrying the offending bytes.
#[test]
fn parse_invalid_mti_non_digit() {
    let wire: &[u8] = b"02XX\x00\x00\x00\x00\x00\x00\x00\x00";
    let err = parse(wire).expect_err("non-digit MTI must fail");
    match err {
        ParseError::InvalidMti(bytes) => assert_eq!(&bytes, b"02XX"),
        other => panic!("expected InvalidMti(b\"02XX\"), got {other:?}"),
    }
}

/// D3. Trailing junk after a valid A3 message -> TrailingBytes { remaining: 2 }.
#[test]
fn parse_trailing_bytes_after_valid_message() {
    let mut wire = cat(&[
        b"0200",
        b"\x40\x00\x00\x00\x00\x00\x00\x00",
        b"16",
        b"4111111111111111",
    ]);
    wire.extend_from_slice(b"\xff\xff");

    let err = parse(&wire).expect_err("trailing bytes must fail");
    match err {
        ParseError::TrailingBytes { remaining } => {
            assert_eq!(remaining, 2, "exactly 2 unexpected trailing bytes");
        }
        other => panic!("expected TrailingBytes {{ remaining: 2 }}, got {other:?}"),
    }
}

/// D4. Builder rejects wrong-length fixed field: field 3 is `Fixed(6)` but we
/// give 5 bytes -> FixedLengthMismatch { field: 3, expected: 6, actual: 5 }.
#[test]
fn build_fixed_length_mismatch_field_3() {
    let m = msg(b"0200", &[(3, b"00000")]); // 5 bytes, must be 6
    let err = build(&m).expect_err("5-byte field 3 must be rejected");
    match err {
        BuildError::FixedLengthMismatch {
            field,
            expected,
            actual,
        } => {
            assert_eq!(field, 3);
            assert_eq!(expected, 6);
            assert_eq!(actual, 5);
        }
        other => panic!(
            "expected FixedLengthMismatch {{ field: 3, expected: 6, actual: 5 }}, got {other:?}",
        ),
    }
}

/// D5 (bonus). Builder rejects unknown field number 200 (out of 1..=128 table).
#[test]
fn build_unknown_or_invalid_field_number() {
    let m = msg(b"0200", &[(200, b"x")]);
    let err = build(&m).expect_err("field 200 is not in the ISO 8583 table");
    assert!(
        matches!(
            err,
            BuildError::UnknownField(200) | BuildError::InvalidFieldNumber(200)
        ),
        "expected UnknownField(200) or InvalidFieldNumber(200), got {err:?}",
    );
}
