//! Build-time code generation for the EBCDIC <-> Unicode codec.
//!
//! Reads the vendored single-byte mapping tables (`tables/cp037.txt` and
//! `tables/cp500.txt`) and emits, into `OUT_DIR/ebcdic_tables.rs`, a pair of
//! `const` arrays per code page:
//!
//!   * a forward table `[u32; 256]` mapping each EBCDIC byte to its Unicode
//!     scalar value, and
//!   * a reverse table `[(u32, u8); 256]` (sorted by scalar) **derived from**
//!     the forward table so the two are provably consistent — there is a
//!     single source of truth (the forward table, itself the vendored
//!     standard). The reverse table is never authored by hand, eliminating
//!     the class of bug where decode and encode disagree.
//!
//! This script uses only `std::fs` / `std::path` (no shelling out) so it is
//! safe on Windows + MSYS2.
//!
//! Scope: single-byte EBCDIC (CP037, CP500). DBCS / mixed SBCS-DBCS code
//! pages (e.g. CP935 / CP1388 for mainframe Chinese) are intentionally NOT
//! handled here — they need a state machine, not a flat table, and are
//! deferred. The table format below has no place for double-byte entries, so
//! a future DBCS effort gets its own generator rather than overloading this.
//!
//! A malformed or short vendored table is a build-time invariant violation
//! and panics with a clear message. This is acceptable (and intended): a
//! broken table must fail the build, never silently ship a half-populated
//! codec. It is build-time only and never reachable at runtime.
//!
//! The workspace `clippy::{panic, unwrap_used, expect_used}` denies target
//! *shipped runtime* code, but this build script is host-only tooling that
//! never runs in any deployed artifact, and failing the build on a corrupt
//! vendored table is exactly the desired fail-fast. The lints are therefore
//! allowed here with this justification.
#![allow(clippy::panic, clippy::unwrap_used, clippy::expect_used)]

use std::fmt::Write as _;
use std::path::Path;

/// Sentinel for an EBCDIC byte that has no mapping in a code page. The
/// vendored tables are complete (all 256 bytes present), so this never
/// appears in practice; the runtime decoder treats it as U+FFFD. Chosen as
/// `u32::MAX`, which is not a valid Unicode scalar, so it can never collide
/// with a real mapping.
const UNDEFINED: u32 = u32::MAX;

/// Number of byte values a single-byte code page covers.
const PAGE_LEN: usize = 256;

fn main() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is always set by cargo");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is always set by cargo");

    let tables_dir = Path::new(&manifest_dir).join("tables");
    let cp037_path = tables_dir.join("cp037.txt");
    let cp500_path = tables_dir.join("cp500.txt");

    // Rerun codegen only when the vendored tables (or this script) change.
    println!("cargo:rerun-if-changed={}", cp037_path.display());
    println!("cargo:rerun-if-changed={}", cp500_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let cp037 = parse_table(&cp037_path);
    let cp500 = parse_table(&cp500_path);

    let mut generated = String::new();
    generated.push_str(
        "// @generated by build.rs from crates/wf-codec/tables/*.txt — do not edit by hand.\n\
         // Forward tables are the vendored Unicode mapping standard; reverse\n\
         // tables are derived from them at build time (single source of truth).\n\n",
    );
    emit_page(&mut generated, "CP037", &cp037);
    emit_page(&mut generated, "CP500", &cp500);

    let out_path = Path::new(&out_dir).join("ebcdic_tables.rs");
    std::fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
}

/// Parse one vendored table file into a forward `[u32; 256]` array.
///
/// Panics (build-time invariant) on any structural problem: missing file,
/// non-`0x` field, out-of-range byte, duplicate or missing byte, wrong line
/// count, or a Unicode field that is not a valid scalar. A flat-out wrong
/// table must break the build, not ship.
fn parse_table(path: &Path) -> [u32; PAGE_LEN] {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read vendored table {}: {e}", path.display()));

    let mut forward = [UNDEFINED; PAGE_LEN];
    let mut seen = [false; PAGE_LEN];
    let mut count = 0usize;

    for (lineno, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let mut fields = line.split_whitespace();
        let byte_field = fields.next().unwrap_or_else(|| {
            panic!(
                "{}:{}: expected '0xXX 0xYYYY', got empty record",
                path.display(),
                lineno + 1
            )
        });
        let scalar_field = fields.next().unwrap_or_else(|| {
            panic!(
                "{}:{}: missing Unicode scalar field in '{}'",
                path.display(),
                lineno + 1,
                line
            )
        });
        if fields.next().is_some() {
            panic!(
                "{}:{}: too many fields in '{}', expected exactly two",
                path.display(),
                lineno + 1,
                line
            );
        }

        let byte = parse_hex(byte_field, path, lineno + 1);
        if byte > u8::MAX as u32 {
            panic!(
                "{}:{}: EBCDIC byte {:#x} out of range 0x00..=0xFF",
                path.display(),
                lineno + 1,
                byte
            );
        }
        let scalar = parse_hex(scalar_field, path, lineno + 1);
        if char::from_u32(scalar).is_none() {
            panic!(
                "{}:{}: {:#x} is not a valid Unicode scalar value",
                path.display(),
                lineno + 1,
                scalar
            );
        }

        let idx = byte as usize;
        if seen[idx] {
            panic!(
                "{}:{}: EBCDIC byte {:#04x} appears more than once",
                path.display(),
                lineno + 1,
                byte
            );
        }
        seen[idx] = true;
        forward[idx] = scalar;
        count += 1;
    }

    if count != PAGE_LEN {
        panic!(
            "{}: expected exactly {} data lines (all bytes 0x00..=0xFF), found {}",
            path.display(),
            PAGE_LEN,
            count
        );
    }
    // `count == PAGE_LEN` with no duplicates guarantees every byte is present,
    // so no UNDEFINED entries remain — the table is total.

    forward
}

/// Parse a `0xXX` / `0XYYYY` hex field into a `u32`. Panics with file/line
/// context on a missing prefix or a non-hex body.
fn parse_hex(field: &str, path: &Path, lineno: usize) -> u32 {
    let body = field
        .strip_prefix("0x")
        .or_else(|| field.strip_prefix("0X"))
        .unwrap_or_else(|| {
            panic!(
                "{}:{}: field '{}' is missing the '0x' prefix",
                path.display(),
                lineno,
                field
            )
        });
    u32::from_str_radix(body, 16).unwrap_or_else(|e| {
        panic!(
            "{}:{}: field '{}' is not valid hex: {e}",
            path.display(),
            lineno,
            field
        )
    })
}

/// Emit the forward and derived-reverse `const` arrays for one code page.
///
/// The reverse table is built here, in build.rs, purely from `forward`, so
/// the encode path can never diverge from the decode path: there is exactly
/// one authored table. The reverse table is emitted sorted by Unicode scalar
/// so the runtime encoder can binary-search it (O(log n), no allocation, no
/// HashMap dependency — keeps the codec std-only).
///
/// Within a single code page each byte maps to a distinct scalar, so the
/// scalar -> byte inverse is unambiguous. We assert that invariant here.
fn emit_page(out: &mut String, name: &str, forward: &[u32; PAGE_LEN]) {
    // Build the reverse pairs (scalar, byte) from the forward table.
    let mut reverse: Vec<(u32, u8)> = Vec::with_capacity(PAGE_LEN);
    for (byte, &scalar) in forward.iter().enumerate() {
        if scalar == UNDEFINED {
            continue;
        }
        reverse.push((scalar, byte as u8));
    }
    reverse.sort_by_key(|&(scalar, _)| scalar);

    // Each scalar must be unique within a page; a duplicate would make encode
    // ambiguous and signals a corrupt vendored table.
    for pair in reverse.windows(2) {
        if pair[0].0 == pair[1].0 {
            panic!(
                "{} reverse table: Unicode scalar {:#06x} maps to two EBCDIC \
                 bytes ({:#04x} and {:#04x}); vendored table is not invertible",
                name, pair[0].0, pair[0].1, pair[1].1
            );
        }
    }

    let upper = name.to_uppercase();

    let _ = writeln!(
        out,
        "/// Forward table for {name}: EBCDIC byte -> Unicode scalar (u32).\n\
         /// `u32::MAX` would mark an undefined byte, but the vendored {name}\n\
         /// table is complete so every entry is a real scalar.\n\
         pub(crate) const {upper}_FORWARD: [u32; {PAGE_LEN}] = ["
    );
    for chunk in forward.chunks(8) {
        out.push_str("    ");
        for &scalar in chunk {
            let _ = write!(out, "0x{scalar:08X}, ");
        }
        out.push('\n');
    }
    out.push_str("];\n\n");

    let _ = writeln!(
        out,
        "/// Reverse table for {name}: (Unicode scalar, EBCDIC byte), sorted by\n\
         /// scalar for binary search. DERIVED from `{upper}_FORWARD` at build\n\
         /// time, so encode and decode share one source of truth.\n\
         pub(crate) const {upper}_REVERSE: [(u32, u8); {len}] = [",
        name = name,
        upper = upper,
        len = reverse.len()
    );
    for chunk in reverse.chunks(6) {
        out.push_str("    ");
        for &(scalar, byte) in chunk {
            let _ = write!(out, "(0x{scalar:08X}, 0x{byte:02X}), ");
        }
        out.push('\n');
    }
    out.push_str("];\n\n");
}
