//! EBCDIC <-> Unicode single-byte codec for mainframe interop.
//!
//! Supports two IBM single-byte EBCDIC code pages:
//!
//! - [`CodePage::Cp037`] — IBM CP037 / ibm-37 (US/Canada).
//! - [`CodePage::Cp500`] — IBM CP500 / ibm-500 ("International"). Identical to
//!   CP037 except at seven byte positions (`0x4A 0x4F 0x5A 0x5F 0xB0 0xBA
//!   0xBB`).
//!
//! The mapping tables are the Unicode Consortium's published character
//! mapping data (see the repository-root `NOTICE`), vendored under
//! `crates/wf-codec/tables/` and compiled in by `build.rs` — there are no
//! runtime dependencies and no I/O on the decode/encode path.
//!
//! # Scope
//!
//! This is **single-byte** EBCDIC only. It does NOT implement an EBCDIC<->GBK
//! bridge, and DBCS / mixed SBCS-DBCS host code pages (e.g. CP935 / CP1388
//! for mainframe Simplified Chinese, which use Shift-Out / Shift-In framing
//! around double-byte runs) are **deferred**. The [`EbcdicDecoder`] type
//! reserves a one-byte-lookahead seam so a future DBCS state machine has a
//! home, but no double-byte logic exists yet.
//!
//! # Round-trip
//!
//! Within a code page, [`decode`] is total (every one of the 256 bytes maps
//! to a Unicode scalar) and [`encode`] is its partial inverse: it succeeds
//! for any character the page can represent and returns an [`EbcdicError`]
//! (never panics) for one it cannot.

use core::fmt;

// Generated by `build.rs` from the vendored tables. Provides, per page:
//   const CP037_FORWARD: [u32; 256]            (byte -> scalar)
//   const CP037_REVERSE: [(u32, u8); N]        (scalar -> byte, sorted)
//   const CP500_FORWARD / CP500_REVERSE        (likewise)
include!(concat!(env!("OUT_DIR"), "/ebcdic_tables.rs"));

/// Replacement character emitted by [`decode`] for a byte with no mapping.
///
/// The vendored tables are complete, so this is unreachable with the built-in
/// pages; it exists so the decode path stays total even if a future,
/// deliberately-sparse table is introduced.
const REPLACEMENT: char = '\u{FFFD}';

/// A supported single-byte EBCDIC code page.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodePage {
    /// IBM CP037 / ibm-37 (US/Canada and many financial hosts).
    Cp037,
    /// IBM CP500 / ibm-500 ("International").
    Cp500,
}

impl CodePage {
    /// The forward (byte -> scalar) table for this page.
    fn forward(self) -> &'static [u32; 256] {
        match self {
            CodePage::Cp037 => &CP037_FORWARD,
            CodePage::Cp500 => &CP500_FORWARD,
        }
    }

    /// The reverse (scalar -> byte) table for this page, sorted by scalar.
    fn reverse(self) -> &'static [(u32, u8)] {
        match self {
            CodePage::Cp037 => &CP037_REVERSE,
            CodePage::Cp500 => &CP500_REVERSE,
        }
    }

    /// Human-readable page name, used in error messages.
    fn name(self) -> &'static str {
        match self {
            CodePage::Cp037 => "CP037",
            CodePage::Cp500 => "CP500",
        }
    }
}

impl fmt::Display for CodePage {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

/// Decode a single EBCDIC byte to its Unicode scalar in `cp`.
///
/// Total: every byte `0x00..=0xFF` maps to a scalar in the built-in pages. A
/// byte with no mapping (impossible with the vendored tables) yields
/// [`REPLACEMENT`] (`U+FFFD`).
fn decode_byte(byte: u8, cp: CodePage) -> char {
    let scalar = cp.forward()[byte as usize];
    char::from_u32(scalar).unwrap_or(REPLACEMENT)
}

/// Decode EBCDIC `bytes` to a [`String`] using code page `cp`.
///
/// This is a total function: there is no error path because every byte in a
/// complete single-byte page has a defined Unicode scalar. Undefined bytes
/// (not present in the built-in pages) decode to `U+FFFD`.
///
/// # Example
///
/// ```
/// use wf_codec::ebcdic::{decode, CodePage};
/// // EBCDIC CP037 0xC8,0xC9 = 'H','I'; 0x40 = space.
/// assert_eq!(decode(&[0xC8, 0xC9, 0x40], CodePage::Cp037), "HI ");
/// ```
pub fn decode(bytes: &[u8], cp: CodePage) -> String {
    let mut out = String::with_capacity(bytes.len());
    for &byte in bytes {
        out.push(decode_byte(byte, cp));
    }
    out
}

/// Encode a Unicode string `s` to EBCDIC bytes using code page `cp`.
///
/// Returns [`EbcdicError::Unrepresentable`] for the first character that has
/// no encoding in `cp`, naming the character, its `char` position, and the
/// page. Never panics.
///
/// # Example
///
/// ```
/// use wf_codec::ebcdic::{encode, CodePage};
/// assert_eq!(encode("HI", CodePage::Cp037).unwrap(), vec![0xC8, 0xC9]);
/// assert!(encode("\u{1F600}", CodePage::Cp037).is_err());
/// ```
pub fn encode(s: &str, cp: CodePage) -> Result<Vec<u8>, EbcdicError> {
    let mut out = Vec::with_capacity(s.len());
    for (position, ch) in s.chars().enumerate() {
        match encode_char(ch, cp) {
            Some(byte) => out.push(byte),
            None => {
                return Err(EbcdicError::Unrepresentable {
                    ch,
                    position,
                    code_page: cp,
                })
            }
        }
    }
    Ok(out)
}

/// Look up the EBCDIC byte for a single character in `cp`, if representable.
///
/// Binary-searches the build-time-derived reverse table (sorted by scalar),
/// so this is O(log n) with no allocation.
fn encode_char(ch: char, cp: CodePage) -> Option<u8> {
    let scalar = ch as u32;
    let table = cp.reverse();
    table
        .binary_search_by_key(&scalar, |&(s, _)| s)
        .ok()
        .map(|idx| table[idx].1)
}

/// Failure modes for [`encode`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EbcdicError {
    /// A character has no representation in the target code page.
    ///
    /// Carries the offending `ch`, its zero-based `char` position in the
    /// input (not its byte offset), and the `code_page` that rejected it —
    /// so a caller knows *what* failed, *where*, and *which page* to switch
    /// to or sanitize against.
    Unrepresentable {
        ch: char,
        position: usize,
        code_page: CodePage,
    },
}

impl fmt::Display for EbcdicError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EbcdicError::Unrepresentable {
                ch,
                position,
                code_page,
            } => write!(
                f,
                "character {:?} (U+{:04X}) at position {} cannot be encoded in {}",
                ch, *ch as u32, position, code_page
            ),
        }
    }
}

impl std::error::Error for EbcdicError {}

/// Bounded, incremental EBCDIC decoder.
///
/// Feed bytes one at a time or in arbitrary chunks; each call appends the
/// decoded characters to the caller's [`String`], so the decoder never
/// buffers the whole input — its own state is O(1) regardless of stream
/// length. For single-byte pages a byte decodes immediately, so the held
/// state is currently always empty.
///
/// # Deferred DBCS seam
///
/// A real EBCDIC mixed SBCS-DBCS stream (CP935 / CP1388) brackets double-byte
/// runs with Shift-Out (`0x0E`) / Shift-In (`0x0F`) and needs one byte of
/// lookahead (the high byte of a double-byte pair) plus a shift-state flag.
/// This type reserves that seam via [`EbcdicDecoder::pending`] and a private
/// shift flag so a future DBCS implementation can grow here without changing
/// the public single-byte API. Today both are unused for the single-byte
/// pages and the decoder is a thin, stateless-in-practice wrapper.
#[derive(Debug, Clone)]
pub struct EbcdicDecoder {
    code_page: CodePage,
    /// One-byte lookahead slot reserved for the deferred DBCS lead byte.
    /// Always `None` for single-byte decoding.
    pending: Option<u8>,
}

impl EbcdicDecoder {
    /// Create a decoder for the given code page.
    pub fn new(cp: CodePage) -> Self {
        EbcdicDecoder {
            code_page: cp,
            pending: None,
        }
    }

    /// The code page this decoder uses.
    pub fn code_page(&self) -> CodePage {
        self.code_page
    }

    /// Decode a chunk of bytes, appending characters to `out`.
    ///
    /// May be called repeatedly with successive chunks; the result is
    /// identical to [`decode`]-ing the concatenation of all chunks. The
    /// decoder holds only O(1) state between calls (a single lookahead slot),
    /// so streaming a multi-gigabyte input never grows the decoder.
    pub fn decode_into(&mut self, bytes: &[u8], out: &mut String) {
        // Single-byte path: every byte decodes immediately; `pending` is
        // reserved for a future DBCS lead byte, asserted empty here
        // (debug-only). When DBCS lands, a held lead byte would be combined
        // with the next incoming byte at this point — no such combination
        // exists yet.
        debug_assert!(self.pending.is_none(), "single-byte decoder holds no state");
        out.reserve(bytes.len());
        for &byte in bytes {
            out.push(decode_byte(byte, self.code_page));
        }
    }

    /// Finish decoding, returning any trailing characters.
    ///
    /// For single-byte pages there is never a dangling lead byte, so this is
    /// always empty. It exists so callers write the same finalize-on-EOF loop
    /// they would need once DBCS (with a possible trailing lead byte error)
    /// is implemented.
    pub fn finish(self) -> String {
        // A held lead byte at EOF would be a truncated double-byte sequence;
        // for single-byte pages `pending` is always None, so nothing trails.
        String::new()
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    // ---- INDEPENDENT external-fact assertions -------------------------------
    // The expected values below come from the published IBM/Unicode EBCDIC
    // standard, NOT from our table-loading code. They assert decode() against
    // known codepoints, so a wrong table or a wrong build.rs would fail here.
    // This is a standards measurement, not a self-consistency check.

    #[test]
    fn cp037_uppercase_letters_match_standard() {
        // EBCDIC is not contiguous over A-Z: A-I = 0xC1..=0xC9,
        // J-R = 0xD1..=0xD9, S-Z = 0xE2..=0xE9.
        let a_to_i = [0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9];
        assert_eq!(decode(&a_to_i, CodePage::Cp037), "ABCDEFGHI");

        let j_to_r = [0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9];
        assert_eq!(decode(&j_to_r, CodePage::Cp037), "JKLMNOPQR");

        let s_to_z = [0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9];
        assert_eq!(decode(&s_to_z, CodePage::Cp037), "STUVWXYZ");
    }

    #[test]
    fn cp037_lowercase_letters_match_standard() {
        let a_to_i = [0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89];
        assert_eq!(decode(&a_to_i, CodePage::Cp037), "abcdefghi");

        let j_to_r = [0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99];
        assert_eq!(decode(&j_to_r, CodePage::Cp037), "jklmnopqr");

        let s_to_z = [0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9];
        assert_eq!(decode(&s_to_z, CodePage::Cp037), "stuvwxyz");
    }

    #[test]
    fn cp037_digits_and_space_match_standard() {
        let digits = [0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9];
        assert_eq!(decode(&digits, CodePage::Cp037), "0123456789");
        // 0x40 is the EBCDIC space (U+0020).
        assert_eq!(decode(&[0x40], CodePage::Cp037), " ");
    }

    #[test]
    fn cp500_shares_letters_and_digits_with_standard() {
        // The letter/digit/space anchors are identical across CP037 and CP500.
        // Bytes: A(0xC1) I(0xC9) J(0xD1) Z(0xE9) a(0x81) z(0xA9) 0(0xF0)
        //        9(0xF9) space(0x40).
        let sample = [0xC1, 0xC9, 0xD1, 0xE9, 0x81, 0xA9, 0xF0, 0xF9, 0x40];
        assert_eq!(decode(&sample, CodePage::Cp500), "AIJZaz09 ");
        assert_eq!(decode(&[0xC1], CodePage::Cp500), "A");
        assert_eq!(decode(&[0x81], CodePage::Cp500), "a");
        assert_eq!(decode(&[0xF0], CodePage::Cp500), "0");
        assert_eq!(decode(&[0x40], CodePage::Cp500), " ");
    }

    // ---- CP037 vs CP500 DIFFERING positions ---------------------------------
    // These seven bytes are the *only* positions where the two pages differ.
    // The exact pairs are read from the two vendored tables (verified, not
    // guessed). Asserting both sides proves the two tables are distinct AND
    // that CodePage selection picks the right one.

    #[test]
    fn cp037_vs_cp500_differ_at_seven_bytes() {
        // (byte, cp037 char, cp500 char)
        let diffs: [(u8, char, char); 7] = [
            (0x4A, '\u{00A2}', '['), // cent  vs '['
            (0x4F, '|', '!'),        // '|'   vs '!'
            (0x5A, '!', ']'),        // '!'   vs ']'
            (0x5F, '\u{00AC}', '^'), // not-sign vs '^'
            (0xB0, '^', '\u{00A2}'), // '^'   vs cent
            (0xBA, '[', '\u{00AC}'), // '['   vs not-sign
            (0xBB, ']', '|'),        // ']'   vs '|'
        ];
        for (byte, c037, c500) in diffs {
            assert_eq!(
                decode(&[byte], CodePage::Cp037).chars().next().unwrap(),
                c037,
                "CP037 byte {byte:#04X}"
            );
            assert_eq!(
                decode(&[byte], CodePage::Cp500).chars().next().unwrap(),
                c500,
                "CP500 byte {byte:#04X}"
            );
            assert_ne!(c037, c500, "byte {byte:#04X} should differ between pages");
        }
    }

    #[test]
    fn cp037_and_cp500_agree_everywhere_except_the_seven() {
        let differing: [u8; 7] = [0x4A, 0x4F, 0x5A, 0x5F, 0xB0, 0xBA, 0xBB];
        for byte in 0u8..=0xFF {
            let same = decode(&[byte], CodePage::Cp037) == decode(&[byte], CodePage::Cp500);
            let expected_same = !differing.contains(&byte);
            assert_eq!(
                same, expected_same,
                "byte {byte:#04X}: CP037/CP500 sameness mismatch"
            );
        }
    }

    // ---- Functional self-consistency (NOT a standards measurement) ----------
    // The following exercise encode/decode against EACH OTHER. They prove the
    // codec is internally consistent (decode ∘ encode = id on representable
    // input), not that any particular byte matches the EBCDIC standard.

    #[test]
    fn printable_ascii_round_trip_self_consistency_cp037() {
        // SELF-CONSISTENCY: encode then decode for every printable ASCII char
        // CP037 can represent must return the original.
        let mut representable = String::new();
        for cp in 0x20u32..=0x7Eu32 {
            if let Some(ch) = char::from_u32(cp) {
                if encode_char(ch, CodePage::Cp037).is_some() {
                    representable.push(ch);
                }
            }
        }
        // CP037 covers all of printable ASCII, so this is the full 0x20..=0x7E.
        assert_eq!(representable.chars().count(), (0x7E - 0x20 + 1) as usize);
        let bytes = encode(&representable, CodePage::Cp037).unwrap();
        let decoded = decode(&bytes, CodePage::Cp037);
        assert_eq!(decoded, representable);
    }

    #[test]
    fn full_byte_round_trip_self_consistency_both_pages() {
        // SELF-CONSISTENCY: decode every byte then re-encode; must recover the
        // original byte (each byte's scalar is unique within a page).
        for cp in [CodePage::Cp037, CodePage::Cp500] {
            for byte in 0u8..=0xFF {
                let s = decode(&[byte], cp);
                let back = encode(&s, cp).unwrap();
                assert_eq!(back, vec![byte], "{cp} byte {byte:#04X} round-trip");
            }
        }
    }

    // ---- encode error path (no panic) ---------------------------------------

    #[test]
    fn encode_rejects_unrepresentable_char() {
        // U+1F600 (emoji) has no EBCDIC representation -> error, not panic.
        let err = encode("AB\u{1F600}CD", CodePage::Cp037).unwrap_err();
        match err {
            EbcdicError::Unrepresentable {
                ch,
                position,
                code_page,
            } => {
                assert_eq!(ch, '\u{1F600}');
                assert_eq!(position, 2);
                assert_eq!(code_page, CodePage::Cp037);
            }
        }
    }

    #[test]
    fn encode_error_message_names_char_position_and_page() {
        let err = encode("\u{1F600}", CodePage::Cp500).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("U+1F600"),
            "message should name the codepoint: {msg}"
        );
        assert!(
            msg.contains("position 0"),
            "message should give position: {msg}"
        );
        assert!(msg.contains("CP500"), "message should name the page: {msg}");
    }

    // ---- streaming decoder (functional self-consistency) --------------------

    #[test]
    fn streaming_decode_matches_one_shot() {
        // Build a representative input covering letters, digits, space, and
        // the differing bytes.
        let input: Vec<u8> = (0u8..=0xFF).collect();
        for cp in [CodePage::Cp037, CodePage::Cp500] {
            let one_shot = decode(&input, cp);

            // Feed the stream in awkward chunk sizes to exercise boundaries.
            let mut dec = EbcdicDecoder::new(cp);
            let mut streamed = String::new();
            for chunk in input.chunks(7) {
                dec.decode_into(chunk, &mut streamed);
            }
            streamed.push_str(&dec.finish());
            assert_eq!(streamed, one_shot, "{cp} streaming != one-shot");
        }
    }

    #[test]
    fn streaming_decoder_state_is_bounded() {
        // After processing arbitrarily many bytes, the decoder holds no
        // accumulated buffer (single-byte: pending stays None). This asserts
        // the O(1)-state / bounded property.
        let mut dec = EbcdicDecoder::new(CodePage::Cp037);
        let mut sink = String::new();
        for _ in 0..1000 {
            dec.decode_into(&[0xC1; 64], &mut sink);
        }
        // The decoder itself carries no per-input growth; `finish` yields
        // nothing because no lead byte is ever pending.
        assert_eq!(dec.clone().finish(), "");
        assert_eq!(sink.chars().count(), 1000 * 64);
    }
}
